version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
<<<<<<< HEAD
    image: udagram-frontend:local
=======
    image: udagram-frontend:local
    
>>>>>>> 90702b3a3c6da43865960255e40048e3b8dd93a6
